-- MySQL Script generated by MySQL Workbench
-- Sat Jun 20 21:49:56 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ironvault
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ironvault
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ironvault` DEFAULT CHARACTER SET utf8 ;
USE `ironvault` ;

-- -----------------------------------------------------
-- Table `ironvault`.`userstbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ironvault`.`userstbl` (
  `iduserstbl` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `namefirst` VARCHAR(45) NULL,
  `namelast` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `passwordhash` VARCHAR(64) NULL,
  PRIMARY KEY (`iduserstbl`),
  UNIQUE INDEX `iduserstbl_UNIQUE` (`iduserstbl` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ironvault`.`categoriestbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ironvault`.`categoriestbl` (
  `idcategoriestbl` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoryname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoriestbl`),
  UNIQUE INDEX `idcategoriestbl_UNIQUE` (`idcategoriestbl` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ironvault`.`fmemberstbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ironvault`.`fmemberstbl` (
  `idfmemberstbl` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fmembername` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfmemberstbl`),
  UNIQUE INDEX `idfmemberstbl_UNIQUE` (`idfmemberstbl` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ironvault`.`loginstbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ironvault`.`loginstbl` (
  `iduserstbl` INT UNSIGNED NOT NULL,
  `categoryid` INT UNSIGNED NULL,
  `fmemberid` INT UNSIGNED NULL,
  `website` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  INDEX `iduserstbl_idx` (`iduserstbl` ASC) VISIBLE,
  INDEX `categoryid` (`categoryid` ASC) INVISIBLE,
  INDEX `idfmemberstbl_idx` (`fmemberid` ASC) VISIBLE,
  CONSTRAINT `FK _userstbl_loginstbl`
    FOREIGN KEY (`iduserstbl`)
    REFERENCES `ironvault`.`userstbl` (`iduserstbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcategoriestbl`
    FOREIGN KEY (`categoryid`)
    REFERENCES `ironvault`.`categoriestbl` (`idcategoriestbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idfmemberstbl`
    FOREIGN KEY (`fmemberid`)
    REFERENCES `ironvault`.`fmemberstbl` (`idfmemberstbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ironvault`.`usersalttbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ironvault`.`usersalttbl` (
  `iduserstbl` INT UNSIGNED NOT NULL,
  `uniquesalt` VARCHAR(64) NOT NULL,
  `userstbl_iduserstbl` INT UNSIGNED NOT NULL,
  INDEX `fk_usersalttbl_userstbl1_idx` (`iduserstbl` ASC) VISIBLE,
  CONSTRAINT `fk_usersalttbl_userstbl1`
    FOREIGN KEY (`iduserstbl`)
    REFERENCES `ironvault`.`userstbl` (`iduserstbl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
